### ISSUE TITLE
Turn Settings Options 2:4 into Parameter Options rather than Client Options

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#35]
We do not want the user to mess around with these settings, so they should be settable from the server, as JSON parameters that are sent along.
Settings 2:4; 
Setting:Default: JSON paramater: JSON type

Play White Noise: True: white_noise : boolean
Inactivity Delay: 30mins (1800s) : session_start_delay : integer (s)
Reset Last Practiced Date: No

**Comment by bcooper94** [comment]
One possibly annoying side effect of having to wait for the white_noise boolean from the server is that either the white noise should not start until the server's response is received, or it should stop if it receives white_noise = false from the server. In the first case, the white noise abruptly stops as you transition from the Volume screen to the Sleep screen, and then abruptly starts again if white_noise is true. In the second case, the white noise continues to smoothly play into Sleep mode, but then abruptly stops as the response is received from the server.

Do you have any preference on which option you'd prefer? I can ramp up the volume from 0 so the startup  isn't so abrupt as well. I might be able to ramp the volume down to 0 during the transition from the Volume screen to the Sleep screen so that the ending isn't abrupt either.

Another question: The reset last practiced date button is pretty useful for debugging. Should I keep it in the DEBUG builds only?

**Comment by sanchezdanj** [comment]
White Noise: We should employ the second case. White noise keeps playing, until it gets a "false" flag from the server.  Annoying, but it'll be fine.  I'm not 100% sure we'll use it. If you want to do some sort of "ramp down" then that's good too. 

Reset Last Button: Just ditch it. I'll setup a "debug" user based on corticalre that we can use that has "all_words=True" which serves the same purpose. @bcooper94 does that work?

**Comment by sanchezdanj** [comment]
@bcooper94 I noticed that the app crashes when there is no white noise. I think this might have something to do with the calculations to ramp white noise volume up and down.

**Comment by bcooper94** [comment]
Finished in version 1.01.
