### ISSUE TITLE
Home to App from App Drawer Opens New Activity

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#36]
Inconsistent Bug!

When the app is running, if you leave it by hitting HOME and then open the app from the app drawer, SOMETIMES the app opens to a new instance!

**Comment by AddictArts** [comment]
Due to the words fetching being an asynchronous task, so unknown when it is done and in the background, the app now takes the option of just returning to main. You start over since pausing is not defined until the sleep activity is under way with words. The issue occurs from my understanding when it is in the limbo of the async fetch for words. That is happening outside the activity.

This will be in the next release.
